name: .NET CI

on:
  push:
    branches:
      - GitActionBranch
jobs:
 build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Your descriptive step name
        run: echo "Hello, GitHub Actions!"
